name: CI [Ubuntu]

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Unzipper
      run: sudo apt-get install unzip -y
    - name: Download
      run: wget -O ngrok.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Install Libraries
      run: |
       sudo apt update
       sudo apt install openssh-server
       sudo apt install xrdp
       sudo apt install slim lxde
    - name: Creating New User
      run: |
        user=mitsuaa
        password=mitsu00
        sudo adduser --quiet --disabled-password --shell /bin/bash --home /home/$user --gecos "User" $user
        # set password
        echo "$user:$password" | sudo chpasswd
        echo User: $user has been created with password: $password
        sudo usermod -aG sudo $user
        #SCRIPT END
    - name: Config RDP in Ubuntu(XRDP)
      run: |
       sudo ufw allow 3389/tcp #setting tcp port 
    - name: Run Bash
      run: sudo echo "slim" > /home/mitsuaa/.xesession
    - name: Starting XRDP
      run: |
        sudo service slim start
        sudo adduser xrdp ssl-cert
        sudo service xrdp restart
        sudo service xrdp status
    - name: Make Ngrok Executable
      run: sudo cp ./ngrok /usr/bin/ngrok
    - name: Auth
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: ngrok authtoken $NGROK_AUTH_TOKEN
#      run: ngrok config add-authtoken $Env:NGROK_AUTH_TOKEN

    - name: Create Tunnel
      run: ngrok tcp 3389
